### ISSUE TITLE
A bit more help

### ISSUE THREAD

**Issue by mdelgadov** [Microsoft/ngconf2015demo#22]
I don't know if I'm missing something:

I tried node tsc/tsc.js from my command line and the node cli and got:

> tsc/tsc.js
> ReferenceError: tsc is not defined
>     at repl:1:2
>     at REPLServer.self.eval (repl.js:110:21)
>     at Interface.<anonymous> (repl.js:239:12)
>     at Interface.emit (events.js:95:17)
>     at Interface._onLine (readline.js:202:10)
>     at Interface._line (readline.js:531:8)
>     at Interface._ttyWrite (readline.js:760:14)
>     at ReadStream.onkeypress (readline.js:99:10
>     at ReadStream.emit (events.js:98:17)
>     at emitKey (readline.js:1095:12)

So, I skipped this step assuming VS 2015 CTP 6 would have typescript set up.

Didn't install the http server because VS2015 has IIS express and usually fits all my needs, also, haven't gotten to the point of something ready to be run, so didn't think it's relevant yet.

Ran the script:vs\VSDevMode.ps1 -vsVersion 14 -tsScript tsc\ and apparently did it properly:

Enabled custom TypeScript language service at C:\Users\Miguel\Documents\Visual Studio 2015\Projects\ngconf2015demo-maste
r\tsc\typescriptServices.js for Dev14
Enabled custom TypeScript default library at C:\Users\Miguel\Documents\Visual Studio 2015\Projects\ngconf2015demo-master
\tsc\lib.d.ts for Dev14
Enabled custom TypeScript default ES6 library at C:\Users\Miguel\Documents\Visual Studio 2015\Projects\ngconf2015demo-ma
ster\tsc\lib.es6.d.ts for Dev14
PS C:\Users\Miguel\Documents\Visual Studio 2015\Projects\ngconf2015demo-master>

Opened the web site and TS files are not recognized. I tried to run but only says "Loading"

So, I'm a bit confused: Do the node tsc command at the begining is necessary for VS 2015 CTP?

Should I use the http server? Doesn't seem necessary for VS but I'm heavily dependent on VS.

What am I missing?

Thanks in advance

**Comment by mdelgadov** [comment]
Solved!
Notes: the node tsc/tsc.js has to be done from the github folder... it is executing the file tsc.js in the folder tsc... we, lowly pampered windows devs don't use the ultraadvanced cli!

the http server has to be used, iis express won't work....

check this blog post, for more help: http://blogs.msdn.com/b/visualstudio/archive/2015/03/12/a-preview-of-angular-2-and-typescript-in-visual-studio.aspx
