### ISSUE TITLE
es6-module-loader@0.16.5.js: error: Cannot resolve all parameters for TodoApp.

### ISSUE THREAD

**Issue by Benjamin-FC** [Microsoft/ngconf2015demo#25]
1) First, I had issues with missing file "lib.es6.d.ts" from tsc folder.
I manually added the file from github and completed powershell script. 

2) Upon running the app in VS 2013 Ultimate with update 4,
getting several errors:

angular2-bundle.js:9838 Cannot resolve all parameters for TodoApp. Make sure they all have valid type or annotations.

-----async gap-----
Error
    at Function.getStacktraceWithUncaughtError (http://localhost:5495/angular2/angular2-bundle.js:699:32)
    at Zone.longStackTraceZone.fork (http://localhost:5495/angular2/angular2-bundle.js:758:43)
    at Zone.bind (http://localhost:5495/angular2/angular2-bundle.js:64:21)
    at Function.Zone.bindArguments (http://localhost:5495/angular2/angular2-bundle.js:195:22)
    at t.obj.(anonymous function) [as then](http://localhost:5495/angular2/angular2-bundle.js:186:42)
    at Compiler.$__export.compileInHost (http://localhost:5495/angular2/angular2-bundle.js:29258:82)
    at DynamicComponentLoader.$__export.loadIntoNewLocation (http://localhost:5495/angular2/angular2-bundle.js:18504:54)
    at http://localhost:5495/angular2/angular2-bundle.js:29514:37
    at Function.$__export.apply (http://localhost:5495/angular2/angular2-bundle.js:10108:23)
    at _AsyncInjectorStrategy._findOrCreate (http://localhost:5495/angular2/angular2-bundle.js:26287:38)

**Comment by vladima** [comment]
Can you please provide more context about how do you get these errors?
I've done the following:
- got a clean copy of ngconf2105demo repo: git clone https://github.com/Microsoft/ngconf2015demo.git
- change current folder to ngconf2015demo: cd ngconf2105demo
- compiled todo.ts: node tsc\tsc.js
- started http server: http-server -p 8080
- opened 'localhost:8080' in chrome

Each step was completed without errors.

**Comment by Benjamin-FC** [comment]
Thanks for the looking into this. I did a clean build again, This time I am getting these errors. 

Uncaught SyntaxError: Unexpected identifier
angular2-bundle.js:752 Error evaluating http://localhost:8080/todo.js
Uncaught SyntaxError: Unexpected identifier
angular2-bundle.js:752 TypeError: Error loading "todo" at http://localhost:8080/todo.js
Cannot read property 'split' of undefined
angular2-bundle.js:753 TypeError: Error loading "todo" at http://localhost:8080/todo.js
Cannot read property 'split' of undefined
    at Zone.longStackTraceZone.getLongStacktrace (http://localhost:8080/angular2/angular2-bundle.js:728:35)
    at Zone.longStackTraceZone.onError (http://localhost:8080/angular2/angular2-bundle.js:753:19)
    at Zone.run (http://localhost:8080/angular2/angular2-bundle.js:92:14)
    at zoneBoundFn (http://localhost:8080/angular2/angular2-bundle.js:66:19)
    at D (https://jspm.io/es6-module-loader@0.16.5.js:1:7439)
    at I (https://jspm.io/es6-module-loader@0.16.5.js:1:7071)
    at O.when (https://jspm.io/es6-module-loader@0.16.5.js:1:10745)
    at w.run (https://jspm.io/es6-module-loader@0.16.5.js:1:9781)
    at e._drain (https://jspm.io/es6-module-loader@0.16.5.js:1:1740)
    at drain (https://jspm.io/es6-module-loader@0.16.5.js:1:1394)
--- Mon Apr 27 2015 10:56:02 GMT-0400 (Eastern Daylight Time) - 39ms ago
Error
    at Function.getStacktraceWithUncaughtError (http://localhost:8080/angular2/angular2-bundle.js:699:32)
    at Zone.longStackTraceZone.fork (http://localhost:8080/angular2/angular2-bundle.js:758:43)
    at Zone.bind (http://localhost:8080/angular2/angular2-bundle.js:64:21)
    at Function.Zone.bindArguments (http://localhost:8080/angular2/angular2-bundle.js:195:22)
    at t.obj.(anonymous function) [as then](http://localhost:8080/angular2/angular2-bundle.js:186:42)
    at k (https://jspm.io/es6-module-loader@0.16.5.js:1:21515)
    at https://jspm.io/es6-module-loader@0.16.5.js:1:22664
    at Zone.run (http://localhost:8080/angular2/angular2-bundle.js:89:19)
    at zoneBoundFn (http://localhost:8080/angular2/angular2-bundle.js:66:19)
    at D (https://jspm.io/es6-module-loader@0.16.5.js:1:7439)
--- Mon Apr 27 2015 10:56:02 GMT-0400 (Eastern Daylight Time) - 41ms ago
Error
    at Function.getStacktraceWithUncaughtError (http://localhost:8080/angular2/angular2-bundle.js:699:32)
    at Zone.longStackTraceZone.fork (http://localhost:8080/angular2/angular2-bundle.js:758:43)
    at Zone.bind (http://localhost:8080/angular2/angular2-bundle.js:64:21)
    at Function.Zone.bindArguments (http://localhost:8080/angular2/angular2-bundle.js:195:22)
    at t.obj.(anonymous function) [as then](http://localhost:8080/angular2/angular2-bundle.js:186:42)
    at x.import (https://jspm.io/es6-module-loader@0.16.5.js:1:22539)
    at x.e.import (https://jspm.io/system@0.16.7.js:5:1180)
    at http://localhost:8080/:34:22
angular2-bundle.js:752 TypeError: Cannot read property '__useDefault' of undefined
angular2-bundle.js:753 TypeError: Cannot read property '__useDefault' of undefined
    at https://jspm.io/system@0.16.7.js:5:1220
    at Zone.run (http://localhost:8080/angular2/angular2-bundle.js:89:19)
    at zoneBoundFn (http://localhost:8080/angular2/angular2-bundle.js:66:19)
    at D (https://jspm.io/es6-module-loader@0.16.5.js:1:7439)
    at I (https://jspm.io/es6-module-loader@0.16.5.js:1:7071)
    at O.when (https://jspm.io/es6-module-loader@0.16.5.js:1:10745)
    at w.run (https://jspm.io/es6-module-loader@0.16.5.js:1:9781)
    at e._drain (https://jspm.io/es6-module-loader@0.16.5.js:1:1740)
    at drain (https://jspm.io/es6-module-loader@0.16.5.js:1:1394)
    at MutationObserver.t (https://jspm.io/es6-module-loader@0.16.5.js:1:3302)
--- Mon Apr 27 2015 10:56:02 GMT-0400 (Eastern Daylight Time) - 43ms ago
Error
    at Function.getStacktraceWithUncaughtError (http://localhost:8080/angular2/angular2-bundle.js:699:32)
    at Zone.longStackTraceZone.fork (http://localhost:8080/angular2/angular2-bundle.js:758:43)
    at Zone.bind (http://localhost:8080/angular2/angular2-bundle.js:64:21)
    at Function.Zone.bindArguments (http://localhost:8080/angular2/angular2-bundle.js:195:22)
    at t.obj.(anonymous function) [as then](http://localhost:8080/angular2/angular2-bundle.js:186:42)
    at x.e.import (https://jspm.io/system@0.16.7.js:5:1195)
    at http://localhost:8080/:34:22

**Comment by paulvanbladel** [comment]
Definitely a bug. My intuition is that it has to do with the dependency injection.
Not really a bug in this very sample but in the angular beta code base.

**Comment by paulvanbladel** [comment]
are you compiling with --emitDecoratorMetadata flag?
That solved the issue for me.
So: tsc --watch -m commonjs -t es5 --emitDecoratorMetadata todo.ts

**Comment by Benjamin-FC** [comment]
Thanks for the help. I am not actively working on this , decided to wait till Angular 2 stabilize.
